# Generated by Django 5.0 on 2023-12-17 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(max_length=20000, verbose_name='Описание')),
                ('image', models.CharField(max_length=200, verbose_name='Фото')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('image', models.CharField(max_length=200, verbose_name='Фото')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('prod_category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='webapp.prodcategory', verbose_name='Категория')),
            ],
        ),
    ]
